# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce23dd3b371c3be1f375e85e4d2b0c569108937260c9bd971b68829296eb8708651749c99648e3d7b192b4ae7df23ad715546b79c62fb466d1b498d24391c8e0

test:
  secret_key_base: 2d56d29f1bd9e3bcc72c18afd72c26eee3aa2f9ec72325a2f1f83c5f26cc50d76a99fa80a7db96cf73c8492fd27ce3e4dd82d0a0e813a34bb8230b4fcbaaf58d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
